//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace LetsFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Airline()
        {
            this.Ratings = new HashSet<Rating>();
            this.Flights = new HashSet<Flight>();
        }
    
        public int AirlineId { get; set; }
        [Required]
        [Display(Name = "Airline Name")]
        public string AirlineName { get; set; }
        [Required]
        [Display(Name = "Image")]
        public string AirlineImg { get; set; }

        [Required]
        [Display(Name = "Airline Code")]
        public string AirlineCode { get; set; }
        [Required]
        [Display(Name = "Airline Description")]
        public string AirlineDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flight> Flights { get; set; }
    }
}
