//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LetsFly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airport
    {
        public int AirportId { get; set; }
        public string AirportName { get; set; }
        public string AirportCode { get; set; }
        public string AirportLocationName { get; set; }
        public string AirportLong { get; set; }
        public string AirportLat { get; set; }
        public Nullable<int> FlightId { get; set; }
    
        public virtual Flight Flight { get; set; }
    }
}
