//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace LetsFly.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int RatingId { get; set; }
        public int RatingNumber { get; set; }
        public string RatingImg { get; set; }
        public string RatingDate { get; set; }
        [Required]
        [AllowHtml]
        public string RatingDescription { get; set; }
        public int UserId { get; set; }
        public int AirlineId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Airline Airline { get; set; }
    }
}
